spring:
  application:
    name: heima-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
logging:
  level:
    org.springframework.ai.chat.advisor: debug
    com.kkk.heimaai: debug